image: golang:latest

stages:
  - test
  - build

format:
  stage: test
  tags:
    - go
    - shell
  script:
    - go fmt ./...
    - go vet ./...

unit:
  stage: test
  tags:
    - go
    - shell
    - gitlab
  script:
    - go test ./...

zip:
  stage: build
  tags:
    - shell
  script:
    - zip -r evalgo.org.eve.zip eve
  artifacts:
    paths:
      - evalgo.org.eve.zip
    expire_in: 1h

