image: golang:latest

stages:
  - test

format:
  stage: test
  tags:
    - go
    - shell
  script:
    - go fmt ./...
    - go vet ./...

unit:
  stage: test
  tags:
    - go
    - shell
    - gitlab
  script:
    - go test ./...
