version: 2

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  enable:
    - errcheck
    - unused
    - ineffassign
    - staticcheck
    - govet

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  errcheck:
    check-blank: false
    check-type-assertions: false
    # Exclude defer/Close patterns in test files
    exclude-functions:
      - (*os.File).Close
      - (*net/http.Response.Body).Close
  staticcheck:
    checks: ["all"]

issues:
  exclude-files:
    - ".*\\.pb\\.go$"
  exclude-dirs:
    - vendor
    - kvm
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - errcheck
    # Allow embedding without using all methods
    - linters:
        - unused
      text: "is unused"
      source: "embed"
    # Exclude all vendor/module dependency errors
    - path: "go/pkg/mod"
      linters:
        - errcheck
        - unused
        - ineffassign
        - staticcheck
        - govet
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false
