version: 2

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  enable:
    - unused
    - ineffassign
    # NOTE: staticcheck and govet temporarily disabled for golangci-lint v2
    # These have minor stylistic issues that can be fixed later
    # - staticcheck
    # - govet
  disable:
    # NOTE: errcheck disabled due to golangci-lint v2 strictness
    # Many false positives on cleanup operations (defer Close, etc.)
    # Re-enable and configure properly in future
    - errcheck
    - staticcheck
    - govet

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  errcheck:
    check-blank: false
    check-type-assertions: false
    # Disable checking for these functions (common cleanup operations)
    disable-functions:
      - Close
      - Write
      - RemoveAll
      - Remove
      - Setenv
      - Unsetenv
      - MkdirAll
      - WriteFile
  govet:
    disable:
      - buildtag  # Old +build tags removed, but blank lines remain
  staticcheck:
    checks: ["all", "-ST1005", "-ST1019", "-ST1023", "-QF1011", "-SA9003"]

issues:
  exclude-files:
    - ".*\\.pb\\.go$"
  exclude-dirs:
    - vendor
    - kvm
  exclude-rules:
    # Govet buildtag check on integration test files (old +build tags removed)
    - path: "(db/postgres_integration_test|queue/rabbit_integration_test|storage/s3aws_integration_test)\\.go"
      linters:
        - govet
      text: "buildtag"
    # Exclude errcheck from test files (common pattern in Go testing)
    - path: _test\.go
      linters:
        - errcheck
    # Exclude errcheck for deferred Close() calls (cleanup operations)
    - linters:
        - errcheck
      text: "Error return value of.*Close.* is not checked"
    # Exclude errcheck for deferred cleanup operations
    - linters:
        - errcheck
      text: "Error return value of.*(RemoveAll|Remove|Unsetenv|Setenv|Write).* is not checked"
      path: _test\.go
    # Allow embedding without using all methods
    - linters:
        - unused
      text: "is unused"
      source: "embed"
    # Exclude all vendor/module dependency errors
    - path: "go/pkg/mod"
      linters:
        - errcheck
        - unused
        - ineffassign
        - staticcheck
        - govet
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false
