codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
        flags:
          - unittests
        paths:
          - "**/*.go"
    patch:
      default:
        target: auto
        threshold: 1%
        base: auto

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

ignore:
  - "**/*_test.go"
  - "**/testdata/**"
  - "**/*.pb.go"
  - "**/vendor/**"
  - "**/examples/**"
